# Библиотекa NumPy

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Petlja/specit4_ai_radni/blob/main/03-biblioteka_numpy.ipynb)

Ова свеска прати лекцију о библиотеци NumPy. У њој можеш да испробаш све функције које су поменуте и изведеш експерименте који су ти занимљиви.

Да би могли да користимо библиотеку NumPy, прво морамо да је учитамо.

In [ ]:
import numpy as np

## Вишедимензиони низови

Основна структура библиотеке NumPy је вишедимензиони низ (енгл. multidimensional array, ndarray). Њу карактеришу облик који указује на димензијe вишедимензионог низа и елементи које садржи. Вишедимензиони низови се креирају позивом функције `array`.

Следећим блоком кода креира се вишедимензиони низ `M` димензија 3x2 тј. која има три врсте и две колоне. Као што смо видели, такве блокове сусрећемо приликом представљања слика али и табеларних података - појединачне колоне означавају атрибуте а врсте инстанце. Вишедимензионе низове који имају две димензије називамо и матрице.

In [ ]:
M = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
])


In [ ]:
M

array([[1, 2],
       [3, 4],
       [5, 6]])

Информацију о димензијама вишедимензионог низа добијамо помоћу својства `shape`.

In [ ]:
M.shape

(3, 2)

Информацију о типу елемената вишедимензионог низа добијамо помоћу својства `dtype`. Сви елементи вишедимензионог низа морају да буду истог типа.

In [ ]:
M.dtype

dtype('int64')

Библиотека NumPy подржава подразумеване типове као што су `int_`, `float_`, `bool_` i `complex_`, али нуди и могућност рада са типовима другачијих опсега и прецизности попут `int8`, `int16`, `uint8`, `float32`, `float64`, `complex128`.

Уколико треба да задамо тип елемената приликом креирања вишедимензионог низа можемо да искористимо додатни аргумент `dtype` функције `array`.

In [ ]:
M = np.array([
  [1, 2],
  [3, 4],
  [5, 6]
], dtype='int64')


In [ ]:
M

array([[1, 2],
       [3, 4],
       [5, 6]])

Ево још неких примера креирања вишедимензионих низова:

- низ једноцифрених бројева

In [ ]:
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- матрица димензија 1x3 која садржи бројеве 10, 11 и 12

In [ ]:
np.array([
    [10, 11, 12]
])

array([[10, 11, 12]])

- матрица димензија 3x1 која садржи бројеве 10, 11 и 12

In [ ]:
np.array([
    [10],
    [11],
    [12]
])

array([[10],
       [11],
       [12]])

## Приступ елементима вишедимензионих низова

Појединачним елементима низова приступа се коришћењем одговарајућих индекса.

Са `M[0,0]` очитавамо вредност у нултој врсти и нултој колони матрице `M`.

In [ ]:
M[0,0]

1

Са `M[2,1]` очитавамо вредност у другој врсти и првој колони матрице `M`.

In [ ]:
M[2,1]

6

Уколико приступимо елементу који не постоји, добићемо грешку!

In [ ]:
M[2,5]

IndexError: ignored

За приступ елементима у библиотеци NumPy може да се користи оператор исецања `:`. Ево неких примера употребе на матрици `A` која је приказана доњом сликом.

![Operator isecanja](./aseti/matrica_operator_isecanja.png)

Прво ћемо матрицу `A` брзо креирати тако што ћемо направити низ бројева од 0 до 24 (то можемо урадити уз помоћ функције `arange`), а потом променити њен облик на 5x5 (то можемо урадити помоћу функције `reshape`).

In [ ]:
A = np.arange(0, 25).reshape(5, 5)

Жути блок:

In [ ]:
A[4, :]

array([20, 21, 22, 23, 24])

Црвени блок:

In [ ]:
A[ :, 1::2]

array([[ 1,  3],
       [ 6,  8],
       [11, 13],
       [16, 18],
       [21, 23]])

Плави блок:

In [ ]:
A[1::2, 0:3:2]

array([[ 5,  7],
       [15, 17]])

Сада и ти можеш да се опробаш и покушаш да издвојиш елементе матрице који су обележени као на доњој слици: прво плаве, затим црвене, потом зелене и на крају љубичасте.

![Operator isecanja vezba](./aseti/matrica_operator_isecanja_vezba.png)

In [ ]:
# Твој ред!

In [ ]:
# Плави блок:

In [ ]:
# Црвени блок:

In [ ]:
# Зелени блок:

In [ ]:
# Љубичасти блок

## Операције над вишедимензионим низовима

Сада ћемо прећи на операције које је могуће изводити над вишедимензионим низовима.

Посматрајмо матрице  $A=\begin{bmatrix}1&3&5\\7&9&11\\13&15&17\end{bmatrix}$ и $B=\begin{bmatrix}2&4&6\\8&10&12\\14&16&18\end{bmatrix}$. \\

Кодови који их креирају су дати ниже.

In [ ]:
A = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

In [ ]:
A

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
B = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

In [ ]:
B

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

Збир ових вишедимензионих низова тј. матрица се добија коришћењем оператора + или функције `add`.

In [ ]:
A + B

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [ ]:
np.add(A, B)

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

Разлика вишедимензионих низова се добија коришћењем оператора `-` или функције `subtract`.

In [ ]:
A - B

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
np.subtract(A, B)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

Вишедимензионе низове можемо да множимо скаларима. За то користимо оператор `*`.

In [ ]:
3*A

array([[ 3,  9, 15],
       [21, 27, 33],
       [39, 45, 51]])

Када множимо матрицу са матрицом, користимо функцију `dot`. Приликом множења матрица морамо да водимо рачуна о слагању димензија.

In [ ]:
A.dot(B)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

Када се примењују математичке функцију библиотеке NumPy над вишедимензионим низовима, оне се примењују над сваким њеним елементом. Тако се, рецимо, извршавањем следећег кода којим се примењује експоненцијална функција `exp` над елементима матрице `M` добијају следеће вредности:

In [ ]:
M

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.exp(M)

array([[  2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003],
       [148.4131591 , 403.42879349]])

Постоји и могућност да се функција изврши само дуж неке димензије вишедимензионог низа, на пример, само по колонама или само по врстама. Наравно, то има смисла само за неке функције као што су проналажење максимума, минимума, сабирање или упросечавање.

Следећим кодом са прво врши сабирање елемената матрице `M` по врстама. За сабирање елемената матрице користи се функција `sum`.

In [ ]:
np.sum(M, axis=1)

array([ 3,  7, 11])

Следећим кодом се врши сабирање елемената матрице `М` по колонама.

In [ ]:
np.sum(M, axis=0)

array([ 9, 12])

Избор одговарајуће димензије у оба случаја нагласили смо коришћењем аргумента `axis`.

## Креирање неких специфичних вишедимензионих низова

Следећи блокови кода илуструју коршћење функција које нам омогућавају да брзо креирамо неке специфичне вишедимензионе низове:

- матрица са случајним бројевима димензије 2x3

In [ ]:
np.random.random((2, 3))

array([[0.75367509, 0.28652712, 0.79622177],
       [0.85791168, 0.82178545, 0.11129668]])

- матрица нула дизмензија 4x4

In [ ]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- матрица јединица димензија 4x2

In [ ]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

- један једнодимензиони низ са еквидистантним скупом 9 тачака из интервала од 0 до 2

In [ ]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Задаци за вежбу

Ево и неких задатака за вежбу.

1. Конструиши матрицу која на главној дијагонали има редом бројеве 1, 2, 3 и 4 а на осталим позицијама нуле. Овакве матрице називамо дијагоналним матрицама.

2. Сада уради исти задатак али бројеве смести на споредну дијагоналу!

3. Одреди вредност просечног елемента матрице.

4. Пронађи највећи елемент у свакој врсти.

5. Пронађи највећи елемент у свакој колони.

Више о садржају и могућностима библиотеке NumPy можеш да пронађеш на званичном сајту http://www.numpy.org/.
